# Note: this docker-compose file is used for building staging/production images on GitHub Actions.
version: '3.8'

services:
  web:
    image: steuerlotse_web:${DOCKER_TAG:-latest}
    build:
      context: ./webapp
      target: webapp
    expose:
      - 5000

  cron:
    image: steuerlotse_cron:${DOCKER_TAG:-latest}
    build:
      context: ./webapp
      target: cron
