version: '3.8'

services:
  nginx:
    build: nginx
    ports:
      - 80:80/tcp

  web:
    build:
      context: ./webapp
      target: webapp
    expose:
      - 5000
    environment:
      - FLASK_ENV=development
      - ERICA_BASE_URL=http://erica:8000/01
      - RATELIMIT_STORAGE_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:secret@postgres:5432/steuerlotse
    volumes:
      - ./webapp:/app:cached

  cron:
    build:
      context: ./webapp
      target: cron
    expose:
      - 5000
    environment:
      - FLASK_ENV=development
      - ERICA_BASE_URL=http://erica:8000/01
      - RATELIMIT_STORAGE_URL=redis://redis:6379/0
      - SQLALCHEMY_DATABASE_URI=postgresql://postgres:secret@postgres:5432/steuerlotse
    volumes:
      - ./webapp:/app:cached

  erica:
    build:
      context: ./erica_app
      args:
        bucket_name: ${ERICA_BUCKET_NAME}
        access_key_id: ${ACCESS_KEY_ID}
        access_key: ${ACCESS_KEY}
        endpoint_url: ${ENDPOINT_URL}
        elster_datenlieferant: ${ELSTER_DATENLIEFERANT}
        elster_hersteller_id: ${ELSTER_HERSTELLER_ID}
    expose:
      - 8000
    environment:
      - ERICA_ENV=development
    volumes:
      - ./erica_app:/app:cached

  redis:
    image: "redis:alpine"
    restart: always

  postgres:
    image: "postgres:alpine"
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: steuerlotse
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
