version: "3.8"

services:
  erica:
    env_file:
      - ".erica.env"
    image: steuerlotse_erica
    expose:
      - 8000
    ports:
      - "8000:8000"
    links:
      - postgres
      - redis
  webapp:
    env_file:
      - ".env"
    build:
      context: "./webapp"
      dockerfile: "Development.Dockerfile"
    volumes:
      - "./webapp:/app"
    ports:
      - "5000:5000"
    links:
      - postgres
      - redis
      - erica
  node:
    env_file:
      - ".env"
    build:
      context: "./webapp"
      dockerfile: "node.Development.Dockerfile"
    volumes:
      - "./webapp:/app"
    ports:
      - "3000:3000"
    links:
      - webapp
  migrations:
    env_file:
      - ".env"
    build:
      context: "./webapp"
      dockerfile: "Development.Dockerfile"
    volumes:
      - "./webapp:/app"
    links:
      - postgres
      - redis
    command: bash -c "flask db upgrade && flask populate-database && pybabel extract -F babel.cfg -k _l -o messages.pot . && ./scripts/babel_run.sh"

  redis:
    image: "redis:alpine"
    restart: always
    expose:
      - 6379
    ports:
      - "6379:6379"

  postgres:
    image: "postgres:alpine"
    restart: always
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: steuerlotse
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
