name: Test CI/CD Pipeline

on: push

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  build-staging:
    if: github.event_name == 'push' && github.ref == 'refs/heads/deployment-reporting'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Report Deployment
        uses: satak/webrequest-action@v1.2.3
        env:
          IMAGE_TAG: ${{ github.run_number }}
        with:
          url: https://metrics.ds4g.dev:56780/webhook/7236d63c-d806-43a7-b8fb-540bfe2a222e
          method: POST
          payload: '{"project": "steuerlotse", "version_identifier": "${{ env.IMAGE_TAG }}", "environment": "staging", "link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
          headers: '{"Authentication": "Token ${{ secrets.METRICS_WEBHOOK_TOKEN }}"}'
