name: Test CI/CD Pipeline

on: push

jobs:
  test-reporting:
    if: github.event_name == 'push' && github.ref == 'refs/heads/deployment-reporting'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Report Deployment
        uses: satak/webrequest-action@master
        env:
          IMAGE_TAG: ${{ github.run_number }}
        with:
          url: ${{ secrets.METRICS_DEPLOYMENT_WEBHOOK_URL }}
          method: POST
          payload: '{"project": "steuerlotse", "version_identifier": "${{ env.IMAGE_TAG }}", "environment": "staging", "link": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
          headers: '{"Authorization": "Token ${{ secrets.METRICS_WEBHOOK_TOKEN }}"}'
