name: Production deployment

on:
  workflow_dispatch:
    inputs:
      imageTag:
        description: 'Image tag to deploy'
        required: true

env:
  DOCKER_REGISTRY: ${{ secrets.DOCKER_REGISTRY }}

jobs:
  deploy-production:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to container repository
      uses: docker/login-action@v1
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PWD }}

    - name: Pull deploy images
      run: docker pull ${{ env.DOCKER_REGISTRY }}/steuerlotse_deployment
      shell: bash

    - name: Run deployment
      env:
        NAMESPACE: production
        IMAGE_TAG: ${{ github.event.inputs.imageTag }}
      run: |
        docker run \
        -e DOCKER_REGISTRY='${{ env.DOCKER_REGISTRY }}' \
        -e KUBECONFIG_BASE64='${{ secrets.CI_KUBECONFIG_B64 }}' \
        -e IMAGE_TAG='${{ env.IMAGE_TAG }}' \
        -e NAMESPACE='${{ env.NAMESPACE }}' \
        ${{ env.DOCKER_REGISTRY }}/steuerlotse_deployment steuerlotse
      shell: bash

    - name: Logout of docker container
      run: docker logout ${{ env.DOCKER_REGISTRY }}
